version: 2

project_name: wordgen

before:
  hooks:
    - go mod tidy

builds:
  - id: wordgen
    main: .
    binary: wordgen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: checksums.txt

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    Maintained by Jeremy Hettenhouser <jhettenh@gmail.com>.
