package cmd

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/adrg/xdg"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

const (
	appName                  = "gsea"
	binaryName               = "gsea"
	envPrefix                = "GSEA"
	configBaseName           = "config"
	configExtension          = "toml"
	exampleSectionKey        = "example"
	outputSectionKey         = "output"
	paletteSectionKey        = "palette"
	paletteName              = "Monokai Spectrumish"
	paletteSourceURL         = "https://github.com/borland502/nix-config/blob/main/home-manager/config/colors/monokai.base24.yaml"
	skipConfigLoadAnnotation = "skip-config-load"
)

// Config is the root configuration model consumed by CLI commands.
//
// It is intentionally small and currently contains demo-oriented sections.
// When the CLI takes on a non-sample objective, keep only the sections that
// active commands read and remove the rest from defaultConfig, renderConfig,
// and the starter config generated by init-config.
type Config struct {
	Example ExampleConfig `mapstructure:"example"`
	Output  OutputConfig  `mapstructure:"output"`
	Palette PaletteConfig `mapstructure:"palette"`
}

// ExampleConfig holds the text used by the sample example command.
//
// This section is expected to disappear or be renamed once the CLI is driven
// by real command behavior instead of demonstration output.
type ExampleConfig struct {
	Greeting     string `mapstructure:"greeting"`
	Name         string `mapstructure:"name"`
	Location     string `mapstructure:"location"`
	FavoriteTide string `mapstructure:"favorite_tide"`
}

// OutputConfig contains reusable output toggles shared by commands.
//
// Unlike the sample-only sections, this struct is a reasonable place to keep
// cross-command behavior such as color or verbosity if the CLI grows.
type OutputConfig struct {
	Color     bool `mapstructure:"color"`
	ShowPaths bool `mapstructure:"show_paths"`
}

// PaletteConfig defines the sample palette preview rendered by the example
// command.
//
// If the CLI no longer needs color swatches or themed example output, remove
// this section together with the example command and the corresponding config
// rendering in renderConfig.
type PaletteConfig struct {
	Black  string `mapstructure:"black"`
	Gray   string `mapstructure:"gray"`
	White  string `mapstructure:"white"`
	Pink   string `mapstructure:"pink"`
	Orange string `mapstructure:"orange"`
	Yellow string `mapstructure:"yellow"`
	Green  string `mapstructure:"green"`
	Cyan   string `mapstructure:"cyan"`
	Purple string `mapstructure:"purple"`
}

type paletteEntry struct {
	Key string
	Hex string
}

var errConfigFileNotFound = errors.New("config file not found")

var (
	cfgFile          string
	loadedConfigPath string
	cfg              = defaultConfig()
	searchConfigFile = searchConfigFileInXDGPaths
)

func defaultConfig() Config {
	return Config{
		Example: ExampleConfig{
			Greeting:     "Ahoy",
			Name:         "Captain",
			Location:     "Pacific Ocean",
			FavoriteTide: "rising tide",
		},
		Output: OutputConfig{
			Color:     true,
			ShowPaths: true,
		},
		Palette: defaultPalette(),
	}
}

func defaultPalette() PaletteConfig {
	return PaletteConfig{
		Black:  "#222222",
		Gray:   "#69676c",
		White:  "#f7f1ff",
		Pink:   "#FC618D",
		Orange: "#fd9353",
		Yellow: "#FCE566",
		Green:  "#7BD88F",
		Cyan:   "#5AD4E6",
		Purple: "#948ae3",
	}
}

func (palette PaletteConfig) entries() []paletteEntry {
	return []paletteEntry{
		{Key: "black", Hex: palette.Black},
		{Key: "gray", Hex: palette.Gray},
		{Key: "white", Hex: palette.White},
		{Key: "pink", Hex: palette.Pink},
		{Key: "orange", Hex: palette.Orange},
		{Key: "yellow", Hex: palette.Yellow},
		{Key: "green", Hex: palette.Green},
		{Key: "cyan", Hex: palette.Cyan},
		{Key: "purple", Hex: palette.Purple},
	}
}

func configFileName() string {
	return configBaseName + "." + configExtension
}

func configRelativePath() string {
	return filepath.Join(appName, configFileName())
}

func defaultUserConfigFilePath() string {
	return filepath.Join(xdg.ConfigHome, configRelativePath())
}

func configSourceDescription() string {
	if loadedConfigPath != "" {
		return loadedConfigPath
	}

	return "defaults, environment variables, and flags"
}

func shouldSkipConfigLoad(cmd *cobra.Command) bool {
	return cmd.Annotations[skipConfigLoadAnnotation] == "true"
}

func loadConfig(cmd *cobra.Command) error {
	loader, err := newConfigLoader(cmd)
	if err != nil {
		return err
	}

	loadedConfigPath = ""

	shouldRead, err := configureConfigFile(loader)
	if err != nil {
		return err
	}

	if shouldRead {
		if err := loader.ReadInConfig(); err != nil {
			return fmt.Errorf("read config: %w", err)
		}
		loadedConfigPath = loader.ConfigFileUsed()
	}

	cfg = defaultConfig()
	if err := loader.Unmarshal(&cfg); err != nil {
		return fmt.Errorf("decode config: %w", err)
	}

	return nil
}

func newConfigLoader(cmd *cobra.Command) (*viper.Viper, error) {
	defaults := defaultConfig()
	loader := viper.New()

	loader.SetEnvPrefix(envPrefix)
	loader.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	loader.AutomaticEnv()

	loader.SetDefault(exampleSectionKey+".greeting", defaults.Example.Greeting)
	loader.SetDefault(exampleSectionKey+".name", defaults.Example.Name)
	loader.SetDefault(exampleSectionKey+".location", defaults.Example.Location)
	loader.SetDefault(exampleSectionKey+".favorite_tide", defaults.Example.FavoriteTide)
	loader.SetDefault(outputSectionKey+".color", defaults.Output.Color)
	loader.SetDefault(outputSectionKey+".show_paths", defaults.Output.ShowPaths)

	for _, entry := range defaults.Palette.entries() {
		loader.SetDefault(paletteSectionKey+"."+entry.Key, entry.Hex)
	}

	for _, key := range []string{
		exampleSectionKey + ".greeting",
		exampleSectionKey + ".name",
		exampleSectionKey + ".location",
		exampleSectionKey + ".favorite_tide",
		outputSectionKey + ".color",
		outputSectionKey + ".show_paths",
	} {
		if err := loader.BindEnv(key); err != nil {
			return nil, fmt.Errorf("bind env %s: %w", key, err)
		}
	}

	for _, entry := range defaults.Palette.entries() {
		key := paletteSectionKey + "." + entry.Key
		if err := loader.BindEnv(key); err != nil {
			return nil, fmt.Errorf("bind env %s: %w", key, err)
		}
	}

	if flag := cmd.Flags().Lookup("greeting"); flag != nil {
		if err := loader.BindPFlag(exampleSectionKey+".greeting", flag); err != nil {
			return nil, fmt.Errorf("bind greeting flag: %w", err)
		}
	}
	if flag := cmd.Flags().Lookup("name"); flag != nil {
		if err := loader.BindPFlag(exampleSectionKey+".name", flag); err != nil {
			return nil, fmt.Errorf("bind name flag: %w", err)
		}
	}
	if flag := cmd.Flags().Lookup("location"); flag != nil {
		if err := loader.BindPFlag(exampleSectionKey+".location", flag); err != nil {
			return nil, fmt.Errorf("bind location flag: %w", err)
		}
	}
	if flag := cmd.Flags().Lookup("favorite-tide"); flag != nil {
		if err := loader.BindPFlag(exampleSectionKey+".favorite_tide", flag); err != nil {
			return nil, fmt.Errorf("bind favorite-tide flag: %w", err)
		}
	}
	if flag := cmd.Flags().Lookup("color"); flag != nil {
		if err := loader.BindPFlag(outputSectionKey+".color", flag); err != nil {
			return nil, fmt.Errorf("bind color flag: %w", err)
		}
	}
	if flag := cmd.Flags().Lookup("show-paths"); flag != nil {
		if err := loader.BindPFlag(outputSectionKey+".show_paths", flag); err != nil {
			return nil, fmt.Errorf("bind show-paths flag: %w", err)
		}
	}

	return loader, nil
}

func configureConfigFile(loader *viper.Viper) (bool, error) {
	if cfgFile != "" {
		loader.SetConfigFile(cfgFile)
		return true, nil
	}

	configPath, err := searchConfigFile(configRelativePath())
	if err != nil {
		if errors.Is(err, errConfigFileNotFound) {
			return false, nil
		}

		return false, fmt.Errorf("search config file: %w", err)
	}

	loader.SetConfigFile(configPath)
	return true, nil
}

func searchConfigFileInXDGPaths(relPath string) (string, error) {
	searchPaths := append([]string{xdg.ConfigHome}, xdg.ConfigDirs...)
	searchedPaths := make([]string, 0, len(searchPaths))

	for _, basePath := range searchPaths {
		candidatePath := filepath.Join(basePath, relPath)
		info, err := os.Stat(candidatePath)
		if err == nil {
			if info.IsDir() {
				return "", fmt.Errorf("config path is a directory: %s", candidatePath)
			}

			return candidatePath, nil
		}
		if errors.Is(err, os.ErrNotExist) {
			searchedPaths = append(searchedPaths, filepath.Dir(candidatePath))
			continue
		}

		return "", fmt.Errorf("stat config path %s: %w", candidatePath, err)
	}

	return "", fmt.Errorf("%w: %s", errConfigFileNotFound, strings.Join(searchedPaths, ", "))
}

func writableConfigFilePath() (string, error) {
	if cfgFile != "" {
		if err := os.MkdirAll(filepath.Dir(cfgFile), 0o700); err != nil {
			return "", fmt.Errorf("create config directory: %w", err)
		}
		return cfgFile, nil
	}

	configPath, err := xdg.ConfigFile(configRelativePath())
	if err != nil {
		return "", fmt.Errorf("resolve XDG config path: %w", err)
	}

	return configPath, nil
}

func renderConfig(config Config) string {
	var builder strings.Builder

	fmt.Fprintf(&builder, "# Generated by %s init-config.\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Run the example program with:\n")
	fmt.Fprintf(&builder, "#   %s example\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Override any value with environment variables like:\n")
	builder.WriteString("#   GSEA_EXAMPLE_NAME=\"Harbor Team\"\n")
	builder.WriteString("#   GSEA_OUTPUT_SHOW_PATHS=false\n")
	builder.WriteString("#   GSEA_PALETTE_PURPLE=\"#948AE3\"\n")
	builder.WriteString("#\n")
	builder.WriteString("# Curated palette subset: one black, one gray, one white, and six accents.\n")
	fmt.Fprintf(&builder, "# Palette source: %s\n\n", paletteSourceURL)

	fmt.Fprintf(&builder, "[%s]\n", exampleSectionKey)
	fmt.Fprintf(&builder, "greeting = %q\n", config.Example.Greeting)
	fmt.Fprintf(&builder, "name = %q\n", config.Example.Name)
	fmt.Fprintf(&builder, "location = %q\n", config.Example.Location)
	fmt.Fprintf(&builder, "favorite_tide = %q\n\n", config.Example.FavoriteTide)

	fmt.Fprintf(&builder, "[%s]\n", outputSectionKey)
	fmt.Fprintf(&builder, "color = %t\n", config.Output.Color)
	fmt.Fprintf(&builder, "show_paths = %t\n\n", config.Output.ShowPaths)

	fmt.Fprintf(&builder, "[%s]\n", paletteSectionKey)
	for _, entry := range config.Palette.entries() {
		fmt.Fprintf(&builder, "%s = %q\n", entry.Key, entry.Hex)
	}

	return builder.String()
}
