// Package cmd wires the wordgen command tree and configuration loading.
//
// The package owns the CLI integration layer: Cobra commands, Viper-backed
// configuration, and the starter config generated by init-config. The generate
// command streams the JSON word index instead of materializing the whole file
// in memory, which keeps the common filtering and sampling path efficient.
package cmd
