package appconfig

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/borland502/wordgen/internal/generator"
)

type Config struct {
	Generate GenerateConfig `mapstructure:"generate"`
}

type GenerateConfig struct {
	Dataset   string   `mapstructure:"dataset"`
	Count     int      `mapstructure:"count"`
	MinLength int      `mapstructure:"min_length"`
	MaxLength int      `mapstructure:"max_length"`
	Prefix    string   `mapstructure:"prefix"`
	Contains  string   `mapstructure:"contains"`
	Sources   []string `mapstructure:"sources"`
	Seed      int64    `mapstructure:"seed"`
}

func (config GenerateConfig) ToRequest() generator.Request {
	return generator.Request{
		Dataset:   config.Dataset,
		Count:     config.Count,
		MinLength: config.MinLength,
		MaxLength: config.MaxLength,
		Prefix:    config.Prefix,
		Contains:  config.Contains,
		Sources:   config.Sources,
		Seed:      config.Seed,
	}
}

func Default() Config {
	return Config{
		Generate: GenerateConfig{
			Dataset:   filepath.Join("assets", "all.json"),
			Count:     1,
			MinLength: 4,
			MaxLength: 10,
			Prefix:    "",
			Contains:  "",
			Sources:   nil,
			Seed:      0,
		},
	}
}

func Render(config Config, binaryName string) string {
	var builder strings.Builder

	fmt.Fprintf(&builder, "# Generated by %s init-config.\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Generate words with:\n")
	fmt.Fprintf(&builder, "#   %s generate\n", binaryName)
	builder.WriteString("#\n")
	builder.WriteString("# Override any value with environment variables like:\n")
	builder.WriteString("#   WORDGEN_GENERATE_COUNT=5\n")
	builder.WriteString("#   WORDGEN_GENERATE_PREFIX=\"pre\"\n")
	builder.WriteString("#   WORDGEN_GENERATE_DATASET=\"./assets/all.json\"\n")
	builder.WriteString("#\n")
	builder.WriteString("# Dataset should point at the generated all.json word index.\n\n")

	builder.WriteString("[generate]\n")
	fmt.Fprintf(&builder, "dataset = %q\n", config.Generate.Dataset)
	fmt.Fprintf(&builder, "count = %d\n", config.Generate.Count)
	fmt.Fprintf(&builder, "min_length = %d\n", config.Generate.MinLength)
	fmt.Fprintf(&builder, "max_length = %d\n", config.Generate.MaxLength)
	fmt.Fprintf(&builder, "prefix = %q\n", config.Generate.Prefix)
	fmt.Fprintf(&builder, "contains = %q\n", config.Generate.Contains)
	builder.WriteString("sources = []\n")
	fmt.Fprintf(&builder, "seed = %d\n", config.Generate.Seed)

	return builder.String()
}
