package appconfig

import (
	"strings"
	"testing"
)

func TestGenerateConfigToRequest(t *testing.T) {
	config := GenerateConfig{
		Dataset:   "assets/all.json",
		Count:     7,
		MinLength: 4,
		MaxLength: 10,
		Prefix:    "st",
		Contains:  "ee",
		Sources:   []string{"fsu/wordle.txt"},
		Seed:      123,
	}

	request := config.ToRequest()
	if request.Dataset != config.Dataset ||
		request.Count != config.Count ||
		request.MinLength != config.MinLength ||
		request.MaxLength != config.MaxLength ||
		request.Prefix != config.Prefix ||
		request.Contains != config.Contains ||
		request.Seed != config.Seed {
		t.Fatalf("request mapping mismatch: got %#v, want %#v", request, config)
	}
	if len(request.Sources) != 1 || request.Sources[0] != "fsu/wordle.txt" {
		t.Fatalf("unexpected sources mapping: %#v", request.Sources)
	}
}

func TestRenderIncludesExpectedSections(t *testing.T) {
	text := Render(Default(), "wordgen")

	mustContain := []string{
		"# Generated by wordgen init-config.",
		"[generate]",
		"dataset = \"assets/all.json.zst\"",
		"count = 1",
		"min_length = 4",
		"max_length = 10",
		"sources = []",
	}

	for _, expected := range mustContain {
		if !strings.Contains(text, expected) {
			t.Fatalf("rendered config missing %q", expected)
		}
	}
}
